### ISSUE TITLE
pgfields do not work for sphinx auto doc

### ISSUE THREAD

**Issue by gkappel** [lukesneeringer/django-pgfields#11]
Model fields like 
    id = models.UUIDField(auto_add=True, primary_key=True)
    attributes = models.JSONField(type=dict)

WARNING: autodoc: failed to import attribute u'AModel.id' from module u'app.models'; the following exception was raised: 
AttributeError: id

**Comment by gkappel** [comment]
Workaround, put in sphinx conf.py

```
# Adapted from https://bitbucket.org/birkenfeld/sphinx/issue/1254/autodoc-fails-to-handle-descriptors-with
from django.db.models.fields.subclassing import Creator
Creator.__get__ = lambda self, *args, **kwargs: self
```

**Comment by lukesneeringer** [comment]
I'm confused: Is this something I should be doing _in django-pgfields_ somewhere?

**Comment by gkappel** [comment]
I don't think so, the workaround is just a monkey patch hack to allow sphinx to work, not sure what the correct solution is
