### ISSUE TITLE
auto_add should set value before pre_save

### ISSUE THREAD

**Issue by ghost** [lukesneeringer/django-pgfields#13]
Hello, @lukesneeringer !

Today I tried to use uuid field before saving model instance (for generating upload_image path and filename)

``` python3
def upload_image(instance, filename):
    ext = filename.split('.')[-1]
    if instance:
        key = str(instance.uuid)
    else:
        key = 'r{}'.format(str(uuid.uuid4()))
    now = datetime.now()
    return 'photos/image/{}/{}/{}/{}.{}'.format(now.year, now.month, now.day, key, ext)


class Photo(models.Model):
    """
    Photo
    """
    uuid = UUIDField(verbose_name=_('UUID'), unique=True, auto_add='uuid:uuid1')
    user = models.ForeignKey(User, verbose_name=_('user'), related_name='photos', help_text="User Foreign Key")
    ... 
    image = models.ImageField(_('image'), max_length=255, upload_to=upload_image)
    ... ...
```

And after creating and saving, I found that my filenames are something like that: .jpg, .jpg_1 etc. I think, this is because UUID1 in my case generates on pre_save. 

``` sh
/Users/lorddaedra/.pyenv/versions/byvshie/bin/python -u /Applications/PyCharm.app/helpers/pydev/pydevconsole.py 60871 60872
PyDev console: starting.import sys; print('Python %s on %s' % (sys.version, sys.platform))
Python 3.4.1 (default, Jun 17 2014, 23:29:34) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
sys.path.extend(['/Users/lorddaedra/Projects/byvshie', '/Applications/PyCharm.app/helpers/pycharm', '/Applications/PyCharm.app/helpers/pydev'])
import django_manage_shell; django_manage_shell.run("/Users/lorddaedra/Projects/byvshie")
>>> from byvshiebase.models import *
>>> photo = Photo()
>>> photo
<Photo: >
>>> photo.uuid
''
```

Is it possible to generate UUID1 auto after photo = Photo()? 

My task is generate file name = photo.uuid. This is my current code:

``` python3
# pipeline.py (for python-social-auth)
def load_vk_user_details(strategy, details, response, user=None, *args, **kwargs):
    """Load and update vk user details using data from provider."""
    if user:

        if not user.photo:
            if strategy.backend.name == 'vk-oauth2':
                if 'photo_max_orig' in response:
                    url = response.get('photo_max_orig')
                else:
                    url = get_gravatar_url(user.email, 200)
                photo_r = requests.get(url)
                photo_r.raise_for_status()
                image = ContentFile(photo_r.content)
                photo = Photo(user=user)

                disassembled = urlparse(url)
                filename, file_ext = splitext(basename(disassembled.path))
                photo.image.save(".".join([filename, file_ext]), image)
                user.photo = photo
        ...
        user.save()

```

May be I can directly set photo = Photo(uuid=uuid.uuid1()) (I'm not tested, it will overwrite it on pre_save with new uuid1 value or not) but if I have auto_add in model - it's not good idea to set it manually IMHO... 

So is it good idea to do something with Photo on **init**? Or any pitfails exists?..

**Comment by ghost** [comment]
Or I should try replace auto_add to default https://docs.djangoproject.com/en/dev/ref/models/fields/#default ?..

**Comment by ghost** [comment]
I replaced `uuid = UUIDField(verbose_name=_('UUID'), unique=True, auto_add='uuid:uuid1')` with `uuid = UUIDField(verbose_name=_('UUID'), unique=True, editable=False, default=uuid.uuid1)`

and changed 1 line here: 

```
def get_prep_value(self, value):
    """Return a wrapped, valid UUID value."""

    # If the value is None, return None.
    if not value:
        if self.null or self._auto_add or self.default:  # added `or self.default`
            return None
        raise ValueError('Explicit UUID required unless either `null` is '
                         'True or `auto_add` is given.')

    # If we already have a UUID, pass it through.
    if isinstance(value, uuid.UUID):
        return value

    # Convert our value to a UUID.
    return uuid.UUID(value)
```

It fixes my problem...

**Comment by ghost** [comment]
So IMO we should:
1. add `or self.default` to get_prep_value in source
2. Document all : "if you need auto add uuid, please use editable=False, default=uuid.uuid1 instead of auto_add"
3. deprecate auto_add for Django 1.7+

**Comment by ghost** [comment]
Ahh, and yes, it's compatible with migrations Django 1.7 :-) https://docs.djangoproject.com/en/dev/topics/migrations/#serializing-values

**Comment by lukesneeringer** [comment]
Ideally, `auto_add` should act as much like `default=` as possible. The only reason it's a separate argument is for compatibility with South.

Unfortunately, South isn't going to go away with Django 1.7 – people with legacy code and South migrations will continue to use it, so it's not quite as simple as deprecating it.

I do concur with you that, absent the presence of South, it's important for `auto_add` and `default=` to work the same way.

**Comment by lukesneeringer** [comment]
OK, I've had a chance to look at this more carefully.

My take is:
- I think that `default=uuid.uuid1` or `default=uuid.uuid4` is, in fact, preferable to the use of `auto_add` in Django 1.7+ using Django migrations.
- I think that `auto_add` is still necessary for South, and can't be deprecated yet.

I've definitely made the change you asked for about adding `or self.default`; that's a no-brainer.

**Comment by lukesneeringer** [comment]
I've decided to also add a note in the docs suggesting the use of `default=` if South is not a factor, and with that I think this issue should be solved. Let me know if it's not. :)

**Comment by ghost** [comment]
Hello!

Thank you for fixing this! I suggest set editable to False if default is provided or change documentation (if user going to migrate from auto_add to default, he/she should add editable=False also)        

```
    # If `auto_add` is enabled, it should imply that the field
    # is not editable, and should not show up in ModelForms.
    if auto_add and 'editable' not in kwargs:  # add ... (... or 'default' in kwargs) ...
```

**Comment by ghost** [comment]
And may be if you are interesting (it's just for fun for me but may be helpful for newbie users) it will good idea to add check - if django >= 1.7 and auto_add is provided - add message to user "Hey user! Use default instead of auto_add! bla-bla-bla"
https://docs.djangoproject.com/en/dev/topics/checks/

**Comment by lukesneeringer** [comment]
> And may be if you are interesting (it's just for fun for me but may be helpful for newbie users) it will good idea to add check - if django >= 1.7 and auto_add is provided - add message to user "Hey user! Use default instead of auto_add! bla-bla-bla"

I'm going to hold off on doing something like this for now because you still need `auto_add` if you're using both Django 1.7 and South, which I expect will happen in real life.
