### ISSUE TITLE
Add ability specify JSONField 'type'

### ISSUE THREAD

**Issue by jch-gh** [lukesneeringer/django-pgfields#5]
The purpose of this type argument is to require data saved to a JSONField to conform to a specified type (e.g. dict) to be considered valid.

**Comment by lukesneeringer** [comment]
Hi @jchappell82,
Would you please, at your convenience, please look over #6, and provide any feedback you may have? Thanks.

**Comment by jch-gh** [comment]
I think that takes care of this request.
