### ISSUE TITLE
Django 1.7 admin problem

### ISSUE THREAD

**Issue by ghost** [lukesneeringer/django-pgfields#8]
Hello!

I get admin database error 

```
"Ошибка базы данных
Ваша база данных неправильно настроена. Убедитесь, что соответствующие таблицы были созданы, и что соответствующему пользователю разрешен к ним доступ."
```

if I use 
`from django_pg import models`
 instead of 
`from django.db import models`

(Problem with models.Model if I import it from django_pg)

**Comment by ghost** [comment]
Tested on Python 3.4, Django 1.7b1

**Comment by lukesneeringer** [comment]
Hi there @lorddaedra,
_django-pgfields_ does not yet officially support Django 1.7. However, as Django 1.7 will be released soon, this does need to happen. Thank you for reporting this.

One request: Can you provide me the database error in English, please?

**Comment by ghost** [comment]
@lukesneeringer , I searched in ...django/contrib/admin/locale/ru/LC_MESSAGES/django.po and get this one

```
#: templates/admin/invalid_setup.html:12
msgid ""
"Something's wrong with your database installation. Make sure the appropriate "
"database tables have been created, and make sure the database is readable by "
"the appropriate user."
msgstr ""
"Ваша база данных неправильно настроена. Убедитесь, что соответствующие "
"таблицы были созданы, и что соответствующему пользователю разрешен к ним "
"доступ."
```

Hmm... Invalid setup error...

**Comment by ghost** [comment]
/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/contrib/admin/options.py:1451:

``` python
        try:
            cl = ChangeList(request, self.model, list_display,
                list_display_links, list_filter, self.date_hierarchy,
                search_fields, self.list_select_related, self.list_per_page,
                self.list_max_show_all, self.list_editable, self)

        except IncorrectLookupParameters:
            # Wacky lookup parameters were given, so redirect to the main
            # changelist page, without parameters, and pass an 'invalid=1'
            # parameter via the query string. If wacky parameters were given
            # and the 'invalid=1' parameter was already in the query string,
            # something is screwed up with the database, so display an error
            # page.
            if ERROR_FLAG in request.GET.keys():
                return SimpleTemplateResponse('admin/invalid_setup.html', {
                    'title': _('Database error'),
                })
            return HttpResponseRedirect(request.path + '?' + ERROR_FLAG + '=1')
```

**Comment by lukesneeringer** [comment]
A few questions so I can track this down:
- Is the change in the import the _only_ change being made? It works when you `from django.db import models`?
- What, if any, django_pgfields specific fields are you using?

**Comment by ghost** [comment]
@lukesneeringer Now I use 

``` python
from django.db import models
from django_pg import models as pg_models 

...

class Ex(models.Model):
    """
    Ex
    """
    uuid = pg_models.UUIDField(verbose_name=_('UUID'), unique=True,
                            auto_add='uuid:uuid1')
    first_name = models.CharField(_('first name'), max_length=30, db_index=True)
    last_name = models.CharField(_('last name'), max_length=30, db_index=True)
    birthdate = models.DateField(_('birthdate'), db_index=True)

    # Others (hidden)
    notes = models.TextField(_('notes'), blank=True, db_index=True)
    date_created = pg_models.DateTimeField(_('date created'),
                                        default=timezone.now,
                                        auto_now_add=True, db_index=True)
    date_modified = pg_models.DateTimeField(_('date modified'),
                                         default=timezone.now,
                                         auto_now=True, db_index=True)


    class Meta:
        ordering = ('-id', )

    def __str__(self):
        return '{} {} ({})'.format(self.first_name, self.last_name,
                                   self.birthdate)

    @models.permalink
    def get_absolute_url(self):
        return ('ex', [str(self.uuid)])

```

and it works...

but if I replace 

``` python
from django.db import models
from django_pg import models as pg_models 
```

to

``` python
# from django.db import models
from django_pg import models # as pg_models 
```

and `pg_models` to `models`, I will get error...

**Comment by ghost** [comment]
So I think, it's problem with models.Model if it's imported from django_pg...

**Comment by lukesneeringer** [comment]
So, I've done a decent bit of playing around with django-pgfields on Django 1.7:

The short version is: Django has altered _several_ aspects of how field lookup resolution works, so there are a decent number of issues that django-pgfields will need to update to be Django 1.7 compatible.

I'll be looking into getting a release soon, probably between the first RC and actual release.

**Comment by lukesneeringer** [comment]
Hi @lorddaedra,
Please check out the `django-1.7-unstable` branch (edit: or `pip install django-pgfields==1.5.0a1`) and give it some initial testing. In particular, there were several issues with array fields that broke in django-pgfields against Django 1.7, which I've fixed.

There's still work to do before a release is reasonable: in particular, I need to ensure that Django 1.7 supports the new migrations framework. But I'd be interested to know if you still have the same issue.

**Comment by ghost** [comment]
@lukesneeringer , I installed django-pgfields==1.5.0a1, it works, thank you :-)

If I will find any new bugs, I'll write comment...
